### ISSUE TITLE
wit add-dep on a package that is already in the manifest causes second entry

### ISSUE THREAD

**Issue by richardxia** [sifive/wit#161]
This is on wit 0.10.1.

When you run `wit add-dep` to add a package that is already in the wit-manifest.json, it causes a second entry for that package within the wit-manifest.json. It appears that when wit resolves dependencies, if there are two of the same dependency in the wit-manifest.json, then it'll pick the latter (or perhaps the newest one by git history), so the outward behavior is as expected.

However, I think we should 1) fix `wit add-dep` to just behave like `update-dep` if a package already exists in the manifest and 2) have wit abort if presented with a wit-manifest.json that has the same package listed twice to avoid any unexpected behavior.

**Comment by jackkoenig** [comment]
Fixed by #165
