### ISSUE TITLE
Optimize Wit GitHub Action Docker image size

### ISSUE THREAD

**Issue by richardxia** [sifive/wit#223]
I think there are two things that we can do to minimize the GitHub Action Docker image size:

- Remove the Java dependency altogether, since Wit along the master branch no longer has the Scala plugin
- Switch to an Alpine base image, which will be much smaller. It does actually look like, however, that the newer Ubuntu images are also a lot smaller than 16.04:

    ```sh
    $ docker images | grep ubuntu
    ubuntu          20.04     a3282b72a167        4 weeks ago         73.8MB
    ubuntu          18.04     4e5021d210f6        4 weeks ago         64.2MB
    ubuntu          16.04     96da9143fb18        3 months ago        124MB
    ```

**Comment by mmjconolly** [comment]
Is that download size or on-disk uncompressed?

I'm thinking we only need python and git in the image

**Comment by richardxia** [comment]
According to the docs on [`docker image`](https://docs.docker.com/engine/reference/commandline/images/):

> The SIZE is the cumulative space taken up by the image and all its parent images. This is also the disk space used by the contents of the Tar file created when you docker save an image.

> I'm thinking we only need python and git in the image

Yes, I believe that's true. We could even just start with an official [Python Alpine Docker image](https://hub.docker.com/_/python) so that we only have to install `git`.
