### ISSUE TITLE
New command: wit add-pkg packagename::revision

### ISSUE THREAD

**Issue by samh-sifive** [sifive/wit#31]
If the package does not exist in wit-workspace.json, add the package with the specified revision

If the package does exist in wit-workspace.json, override the revision with the revision specified

**Comment by aaronjanse** [comment]
My understanding is that the second part of the issue has been resolved by lines 237 & 241:

https://github.com/sifive/wit/blob/3ac58113edafad31c4a0ed5f0b147b96d76ecda8/lib/workspace.py#L228-L247

**Comment by jackkoenig** [comment]
@aaronjanse you are correct, this has been implemented
